name: tasktracker

services:
  postgres:
    image: postgres:15.3-alpine
    container_name: tasktracker-postgres
    environment:
      POSTGRES_DB: tasktracker
      POSTGRES_USER: tasktracker
      POSTGRES_PASSWORD: tasktracker
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasktracker -d tasktracker"]
      interval: 5s
      timeout: 3s
      retries: 20
  tracker:
    build: .
    ports:
      - "8082:8081"
    environment:
      port: "8081"
      datasource.url: "jdbc:postgresql://tasktracker-postgres:5432/tasktracker"
    depends_on: [postgres]

volumes:
  pgdata: