server:
  port: ${port:8088}

spring:
  application:
    name: tasktracker-jpa

  datasource:
    url: ${datasource.url:jdbc:postgresql://localhost:5432/tasktracker}
    username: tasktracker
    password: tasktracker
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info
    com.example.tasktracker: debug
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

  file:
    name: ${LOG_FILE:observability/logs/app.log}
#    name: observability/logs/app.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus


