apiVersion: v1
kind: Service
metadata:
  name: promtail-service
spec:
  type: ClusterIP
  selector:
    app: promtail
  ports:
    - name: http
      port: 9080
      targetPort: 9080
  # Service для promtail обычно не обязателен,
  # но иногда удобен для дебага / метрик / health-check.